### ISSUE TITLE
Use `sh` shell

### ISSUE THREAD

**Issue by oprypkhantc** [liskin/gh-workflow-keepalive#1]
Hey.

Currently this uses `bash` shell: https://github.com/liskin/gh-workflow-keepalive/blob/main/action.yml#L18

When running on GitHub hosted runners, it works okay as they contain both `bash` and `gh` CLI. When you try to run the same action on self-hosted runners, they may not have `gh` CLI set up. To counter this, I'm running this action from a container image that has `gh`, but doesn't have `bash` installed: https://github.com/maniator/gh

Of course I could just install `bash` into that image, but I believe a better solution would be to just drop the dependency on `bash`. It's only needed for the first line of the `run`, and although I'm unsure why this condition is necessary, instead of evaluating this result with `bash`, it could be replaced with `if` checks from GH itself: 
`if: ${{ startsWith(github.workflow_ref, format('{0}/.github/workflows/', github.repository)) }}`

Is this something you'll accept as a PR?

**Comment by liskin** [comment]
The point of that line is to make 100% sure that `$GITHUB_WORKFLOW_REF` looks exactly like the following substitutions expect it to, because if it didn't then those substitutions wouldn't substitute anything and that'd be bad. With that in mind, I think it'd be better if we rewrote it to POSIX sh rather than into a GitHub Actions `if:`.

And yeah I'll definitely accept that as a PR.

**Comment by liskin** [comment]
(Also note that https://github.com/marketplace/actions/keepalive-workflow has since been updated to use the same GitHub API as this action uses, so you may also try that.)

**Comment by oprypkhantc** [comment]
Got it. I'm not a devops, so I got very little experience with shells, especially posix. But it seems to be working as expected: https://github.com/liskin/gh-workflow-keepalive/pull/2

And on that other action - it's also broken in the container. Just a failing step - no error message or anything. And I like this implementation more :)
